### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by k-andrew** [onozaty/redmine_issue_assign_notice#1]
How can I set a Slack сhannel?

**Comment by onozaty** [comment]
Channel specification is not supported.
If you want to post to a different channel for each project, create Incoming Webhooks for each channel.

* https://api.slack.com/messaging/webhooks#getting_started

Thanks

**Comment by k-andrew** [comment]
@onozaty Do you plan to add this feature?

**Comment by onozaty** [comment]
Hi @k-andrew 

Sorry, There are no plans.
This is because it is also deprecated in Slack's Incoming Webhooks and we don't know when it will become unavailable.

Thanks.
