### ISSUE TITLE
Doesn't work on redmine 4.2.2

### ISSUE THREAD

**Issue by hiroshi24da** [onozaty/redmine_issue_assign_notice#13]
It seems that notice for Teams doesn't work on redmine 4.2.2.
It works on 4.2.1.

My emvironment: sameersbn/redmine:4.2.2

**Comment by onozaty** [comment]
Thank you for your report.

I've tried to connect with Teams with Redmine 4.2.2 here as well, and there was no problem.
Are there any errors in the Redmine log?

Thanks.

**Comment by hiroshi24da** [comment]
Resolved. Sorry my mistake.
Thanks.
