### ISSUE TITLE
How to setup mentions in MSTeams

### ISSUE THREAD

**Issue by Nestor231** [onozaty/redmine_issue_assign_notice#16]
Hi @onozaty !

Good day!

I have a question, I'm trying to use this plugin in conjunction with MS Teams,

but I don't know what should I supply on the **Assign Notice ID** and how do i retrieve that id, 

I am trying to get the mentions working on MSTeams, How do I do it? 

Thanks!

**Comment by onozaty** [comment]
Hi @Nestor231 

In Teams, Incoming Webhooks do not allow for Mentions.
Therefore, it is not possible to use this plugin for mentioning either.

When Teams supports it, we will consider supporting it in this plugin as well.

Thanks.

**Comment by Nestor231** [comment]
Hello @onozaty 

I appreciate your fast feedback :)

Actually mentions is already supported in their MSTeams incoming webhook

[Please check this link for reference](https://powerusers.microsoft.com/t5/Building-Flows/Unable-to-mention-user-from-Incoming-Webhook/td-p/1227871)

[Using AdaptiveCards For Teams Mention When sending message](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards)

i tested this as well using json and submitted a request to an incoming webhook that i set up with a channel.

Here's the sample json request body  i used for the request: 

```
{
	"type": "message",
	"attachments": [{
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"type": "AdaptiveCard",
			"body": [{
					"type": "TextBlock",
					"size": "Medium",
					"weight": "Bolder",
					"text": "Sample Adaptive Card with User Mention"
				},
				{
					"type": "TextBlock",
					"text": "[Project Name] Hi, <at>Sample_Name</at>. A redmine ticket has been assigned to you."
				}
			],
			"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
			"version": "1.0",
			"msteams": {
                                "width": "Full",
				"entities": [{
					"type": "mention",
					"text": "<at>Sample_Name</at>",
					"mentioned": {
						"id": "<email_registered_on_teams >", // For confidentiality purposes
						"name": "<name_registered_on_teams>"
					}
				}]
			}
		}
	}]
}
```



_From what I learned by playing around with the request body_: 
- in teams, **id** can be the mentioned user's **email address** on teams. ( **Assign Notice ID** can be set as the user's teams email address for this matter) 
- "name" under "mentioned" on the "msteams" field is the display name that will be displayed (FirstName LastName combination from redmine can be displayed as the value)

And here's the result:
![InkedoVmpauhTzI_LI](https://user-images.githubusercontent.com/19929152/149458701-820d1d3b-7f15-43d5-938e-0311a3e96ffb.jpg)

**Comment by onozaty** [comment]
Hi @Nestor231 

Thank you for the information.

I found out that it is supported by Adaptive Cards in Teams.

I would like to consider implementing it.
I think the information you provided will be very helpful in implementation. 

Thank you very much.

**Comment by Nestor231** [comment]
You're welcome @onozaty, 

Have a great day!

**Comment by onozaty** [comment]
Hi @Nestor231 

I'm trying out a small message to see if I can make a mention.

```json
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Hi <at>UserA</at>"
          }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.0",
        "msteams": {
          "entities": [
            {
              "type": "mention",
              "text": "<at>UserA</at>",
              "mentioned": {
                "id": "user@example.com",
                "name": "HogeHoge"
              }
            }
          ]
        }
      }
    }]
}
```

I thought that if I changed the email address in the `id` to the email address used when logging in to Teams as appropriate, I would be able to make a Mention, but it hasn't worked.

![image](https://user-images.githubusercontent.com/47337/150037010-f039ea1f-2798-4a01-9ec1-fefa679f3805.png)

The color of the username part changes, but it does not become a link.
Also, no mentions are made.

If you can find anything strange, I would appreciate your advice.
I am using Teams Free (classic) to verify.

Thanks.

**Comment by Nestor231** [comment]
Hello @onozaty ,

![N6k7whzRLE](https://user-images.githubusercontent.com/19929152/150051610-4de4e84a-4c81-49ae-b31a-98437f0a9d70.png)

![image](https://user-images.githubusercontent.com/19929152/150051453-d4c1d00f-db05-4f77-b660-60e6dbf49a81.png)


I tested your request body, and it's working fine on my end.
I'm not sure if it's because you're using Teams Free. 

I tested  this using **Microsoft Teams Version 1.4.00.32771 (64-bit)**. It was last updated on 12/13/2021.

**Comment by Nestor231** [comment]
I was able to replicate what you did just now.

In my case, i used an email which is not registered within teams.

I am not sure with Teams Free with that behavior. 

What I can infer is that, Teams couldn't find the said email that you used for the mention
or that there's a limitation on Teams Free. I'm not sure which is the case though

**Comment by onozaty** [comment]
Thank you for trying it.

The email address "user@example.com" will be replaced with the email address used to log in to Teams.
It may be a limitation in Teams Free.

**Comment by onozaty** [comment]
Hi @Nestor231 

I have implemented it.
Could you please give it a try?

It is still in branch status.
Please checkout "feature/17-teams-adaptive-cards" and give it a try.

```
git fetch
git checkout feature/17-teams-adaptive-cards
```

Thanks.

**Comment by Nestor231** [comment]
Hello @onozaty , 

Sorry I replied so late,

I have tested it now and,

Yep, It's working! Thanks man ! much appreciated

![InkedDw0fI1oJAK_LI](https://user-images.githubusercontent.com/19929152/151754556-7f6e9c3e-84d4-472d-9e69-e521eedd2c98.jpg)

![InkedBb7xzar2Ey_LI](https://user-images.githubusercontent.com/19929152/151754342-5b89adce-21d9-4c2f-9e98-0d3af8fe989f.jpg)

**Comment by onozaty** [comment]
Thanks for the confirmation!
Thanks to your support, I was able to implement it.

It will be officially released as version 2.1.0 later.

**Comment by onozaty** [comment]
It has been officially released as v2.1.0.

Thanks!

**Comment by Nestor231** [comment]
You're welcome man and thanks! 
Looking forward to more of your projects in the future ^_^

**Comment by Jiemin17** [comment]
Hi @onozaty 
I have the same problem
and I would like to ask how did you solve it in the end

**Comment by onozaty** [comment]
Hi @Jiemin17 
I changed the format of the message so that it can be mentions.

* https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards

What problems do you have?

**Comment by Jiemin17** [comment]
Hi @onozaty 
Thanks for your reply.
My problem is that I can't tag anyone either
My code : 
```
{
    "type": "message",
    "attachments": [
        {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
            "type": "AdaptiveCard",
            "body": [
                {
                    "type": "TextBlock",
                    "size": "Medium",
                    "weight": "Bolder",
                    "text": "Sample Adaptive Card with User Mention"
                },
                {
                    "type": "TextBlock",
                    "text": "try to at <at>me</at> and <at>karenlian</at>"
                }
            ],
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.0",
            "msteams": {
                "entities": [
                    {
                        "type": "mention",
                        "text": "<at>me</at>",
                        "mentioned": {
                          "id": "jie@xxx.biz",
                          "name": "me"
                        }
                      },
                      {
                        "type": "mention",
                        "text": "<at>karenlian</at>",
                        "mentioned": {
                          "id": "karenlian@xxx.biz",
                          "name": "karenlian"
                        }
                      }
                ]
            }
        }
    }]
}
```

![02](https://user-images.githubusercontent.com/91660643/205532654-1cf43726-c98e-4df9-ba72-398324aac356.jpg)
In the picture, although the text has turned blue, the members have not been tagged successfully

**Comment by onozaty** [comment]
Hi @Jiemin17 

I see that the question is not about this plugin.

The format seems to be correct.
If the UPN was wrong, this could happen.
The part specified in mentioned/id.

This is usually the email address used to log in to Teams, but depending on how AD is operated, the UPN may not match the email address.

Thanks.

**Comment by nicoardizzoli** [comment]
Hello there, Someone knows how can i mention @General (and not users). I really need this functionality

**Comment by onozaty** [comment]
> Hello there, Someone knows how can i mention general (and not users). I really need this functionality

Adaptive cards in Teams does not yet seem to support mentions to channels or teams.

* https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#mention-support-within-adaptive-cards

Thanks.

**Comment by nicoardizzoli** [comment]
Thanks @onozaty and do you know how can i make it ? i need to send a notificacion from a backend application (springboot) via webhook to a teams channel, and i need to mark this message as IMPORTANT or mention General to make teams throws a notificacion to the users in this channel

**Comment by onozaty** [comment]
Webhook does not support this, so it will be necessary to use other methods.
For example, the Graph API appears to allow mentions to be made to channels.

* https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=java#example-7--a-channel-in-a-channel-message

Thanks.
