### ISSUE TITLE
Doesn't work with Rocketchat

### ISSUE THREAD

**Issue by Cesar-Morales** [onozaty/redmine_issue_assign_notice#19]
When I add the hook it doesn't send me any message. Can anybody help me?

**Comment by onozaty** [comment]
Are there any error messages in the Redmine logs?
Redmine logs are located in the log directory under the directory where Redmine is installed.

Also, please make sure that Rocket.Chat's Incoming Webhook is enabled, as it is not enabled at the time of creation.

Thanks.

**Comment by Cesar-Morales** [comment]
The webhook is enabled and working, because I use it for another plugin.
I don't see any errors in the logs. When I add the webhook link, it is saved successfully.
But this does nothing in rocket.chat

Log:
```
172.18.0.1 - - [21/Apr/2022:18:12:44 UTC] "GET /settings/plugin/redmine_issue_assign_notice HTTP/1.1" 200 9327
http://localhost:9900/settings/plugin/redmine_issue_assign_notice -> /settings/plugin/redmine_issue_assign_notice
172.18.0.1 - - [21/Apr/2022:18:14:01 UTC] "GET /settings/plugin/redmine_issue_assign_notice HTTP/1.1" 200 9259
- -> /settings/plugin/redmine_issue_assign_notice
172.18.0.1 - - [21/Apr/2022:18:14:03 UTC] "POST /settings/plugin/redmine_issue_assign_notice HTTP/1.1" 302 131
http://localhost:9900/settings/plugin/redmine_issue_assign_notice -> /settings/plugin/redmine_issue_assign_notice
172.18.0.1 - - [21/Apr/2022:18:14:03 UTC] "GET /settings/plugin/redmine_issue_assign_notice HTTP/1.1" 200 9327
http://localhost:9900/settings/plugin/redmine_issue_assign_notice -> /settings/plugin/redmine_issue_assign_notice
```
(The redirection is because to connect redmine and rocket.chat (both in containers) they go through my host)

![Plugin](https://user-images.githubusercontent.com/45375576/164527338-9d469947-5b76-4ab1-8513-8f805e34e214.png)

**Comment by onozaty** [comment]
This plugin will only notify you when the issue assignee changed.
Would not notification also be done when the assignee changed?

Thanks.

**Comment by Cesar-Morales** [comment]
It doesn't notify me of changes I make.
"Set Notice URL for each project?" didn't work for me either

**Comment by onozaty** [comment]
Could you please check to see if any logs were logged when you changed the assignee of the Issue?
It is assumed that the following logs are logged in the event of an error.

```
[RedmineIssueAssignNotice] Failed request to https://example.com/XXXXXXXX
```

**Comment by Cesar-Morales** [comment]
I didn't find any errors, but I'm closing the topic anyway. I found that each project can add what I need in `Settings > Messenger > Outgoing Webhook` and this made it easy for me to send the message. Thank you so much for everything. Greetings

**Comment by ashrafalzyoud** [comment]
how u found this
Settings > Messenger > Outgoing Webhook
@Cesar-Morales
