### ISSUE TITLE
are this plugin work without internet?

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine_issue_assign_notice#21]
my server work in local network,is there any way to work offline internet

**Comment by onozaty** [comment]
If the chat server can be accessed from the Redmine server, it can work.
If the chat server is on the Internet and you can't get to the Internet from Redmine, you can't make it work.

**Comment by ashrafalzyoud** [comment]
Do u know any plugin work offline

**Comment by onozaty** [comment]
Yes, as explained earlier, it is not important to have access to the Internet.
It works if Redmine can access the URL you set as the Incomming WebHook.

**Comment by ashrafalzyoud** [comment]
> Yes, as explained earlier, it is not important to have access to the Internet.
> 
> It works if Redmine can access the URL you set as the Incomming WebHook.

؟!؟!؟
U mean any plugin?!

**Comment by onozaty** [comment]
> U mean any plugin

Sorry, It's about this plugin.

I think there are many plug-ins that work offline.
However, there would be a lot of hassle during installation if you do not have access to the Internet.

**Comment by ashrafalzyoud** [comment]
how i can u se your plugin if offline?

**Comment by onozaty** [comment]
It is available, but you must be connected to the Internet at the time of installation.
If you are not connected to the Internet, bundle install will fail.

**Comment by ashrafalzyoud** [comment]
u mean in installtion for one time then i go offline 
in this case your plugin wotk???

**Comment by onozaty** [comment]
Once online at the time of installation, you can then go offline.

**Comment by ashrafalzyoud** [comment]
That's very good
I will try and tell u results

**Comment by ashrafalzyoud** [comment]
1-  { Mention to assignee? (If is set by others)}

this mean must the user have ID from( google chat,......) NOT depend in assigne_id
----> if im go offline i think just i have one option in project not Mention to assignee? (If is set by others)
becasue in my case its not allowed to have ID CHAT or any things because offline system
or i dont know if its work in assigne_id generate by redmine
2- Assign Notice URL  for project
not work for me im not see any notifications
its must put the value for hooks for all my project or selected ??

**Comment by onozaty** [comment]
> 1- { Mention to assignee? (If is set by others)}

Maybe I am not understanding your question.

This plugin notifies the chat, so you must be able to connect to the chat.
Specifically, Redmine must be able to access the URL of the Incomming WebHook.
You do not need to be connected to the Internet, but you do need to be able to connect to the chat.

To be notified of the mentions, you must

1. assigned to the assignee by another person.
2. the "Assign Notice ID" in the user's custom field is specified as the ID for the chat.

> 2- Assign Notice URL for project

If "Set Notice URL for each project?" is not checked, simply set it to "Notice URL (Incoming Webhook URL)" to enable it for all projects.
If "Set Notice URL for each project?" is checked, then it will only be enabled for the project set as "Assign Notice URL" in the custom field for each project.

**Comment by ashrafalzyoud** [comment]
![wew](https://user-images.githubusercontent.com/50211455/180675768-cdf7c877-7fe5-431c-aab7-aadf5e0dfb7f.png)
when im put the value and apply ,its hide
this normal or no?

**Comment by onozaty** [comment]
This is normal.

If "Set Notice URL for each project?" is checked, the URL cannot be specified on this screen because it must be set as a custom field for each project.

If you want to use the same Incoming WebHook throughout Redmine, uncheck "Set Notice URL for each project?" and specify "Notice URL (Incoming Webhook URL)".

**Comment by ashrafalzyoud** [comment]
thx for u @onozaty 
but in my case i can only connect my server redmine one time just to install plugin
then my redmine discconect internet and work only local network
Servers and PCS in my local network
i think before if this plugin work as server chat

**Comment by onozaty** [comment]
This plugin is used to notify the chat server.
Therefore, a separate chat server must exist.
Also, Redmine must be able to connect to the chat server at all times.
