### ISSUE TITLE
Incoming MS Teams webhook url is working if tested with Postman, but not working in Redmine

### ISSUE THREAD

**Issue by iamriz** [onozaty/redmine_issue_assign_notice#26]
Hi, good day.
I'd like to ask for feedback if possible. 
Incoming MS Teams webhook url is working if tested with Postman, but not working in Redmine.

When checked with the production.log, this I think is the error part. How can we bypass this error? Thank you.
```
[RedmineIssueAssignNotice] Failed request to <MS Teams webhook_url here>
#<SocketError: getaddrinfo .. (xxxxxxx.webhook.office.com:443)>
```

**Comment by onozaty** [comment]
Hi @iamriz 

Can you connect to xxxxxxx.webhook.office.com from the server running Redmine?
Maybe you can connect from your PC but not from Redmine.

Thanks.

**Comment by iamriz** [comment]
Hi @onozaty, thanks for your response. I can connect to xxxxxxx.webhook.office.com from the server running Redmine, I used Postman installed and ran on the redmine server and the webhook url is working fine with Postman but not with Redmine on the same server.

**Comment by onozaty** [comment]
```[RedmineIssueAssignNotice] Failed request to <MS Teams webhook_url here>
#<SocketError: getaddrinfo .. (xxxxxxx.webhook.office.com:443)>
```

Is there a detailed error message output after the `#<SocketError: getaddrinfo`?
If it seems to be omitted in `..`, could you please provide a detailed message?

**Comment by iamriz** [comment]
Hi @onozaty, there is no relevant message after getaddrinfo. I can see some garbage characters, though. 
#<SocketError: getaddrinfo: ?≫?????z?X?g??s????・?B  (xxxxxxx.webhook.office.com:443)>

**Comment by onozaty** [comment]
Sorry, I don't know the error message and therefore don't know the cause.

A common case of this error is when the hostname cannot be resolved.
However, in that case it should not work in Postman either.

Is it some kind of special network environment?

Thanks.

**Comment by iamriz** [comment]
@onozaty , I understand. Thanks for the help. Appreciate it so much.
I am guessing this is a proxy issue on the redmine side as the redmine server is using proxy server to be able to connect to the internet. Will investigate further.

**Comment by onozaty** [comment]
I assume that setting HTTPS_PROXY as an environment variable for the user running Redmine will allow access via Proxy.
