### ISSUE TITLE
Sometimes doesn't notify

### ISSUE THREAD

**Issue by morishima0524** [onozaty/redmine_issue_assign_notice#32]
I changed asignee me to other, other to other, etc... Normaly this plugin notify me assign changed, but sometimes doesn't.

What do you think is the cause?

**Comment by onozaty** [comment]
Will the message not be posted?
Or do you mean that they are not mentions?

**Comment by morishima0524** [comment]
Thank you for replying.

That means no posted.
Plugin worked perfectly when notification is posted.

**Comment by onozaty** [comment]
Thank you for your response.

If the assignee has changed, a message notification should be post to chat.
If there is an error in the WebHook call, it will be output to the log, so could you please check the log as well?

Thanks.

**Comment by morishima0524** [comment]
I found Proxy error in redmine's production.log when notify this plugin.
> WARN -- : [RedmineIssueAssignNotice] Failed request to  MySlackURL
> WARN -- : #<HTTPClient::BadResponseError: connect to the server failed with status 407 Proxy Authentication Required

So, this problem cause my server settings. I'll try change settings.
Sorry and thanks.
